name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
permissions: write-all
jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
                
      - name: Build container  
        run: |
          docker build . --file Dockerfile --tag jaz-test:latest
        
  scan-image:
    needs: build-image
    runs-on: self-hosted
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'jaz-test:latest'
          hide-progress: false
          format: 'sarif'
          ignore-unfixed: true
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
#
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif' 
  
  # run-container:
  #   needs: scan-image
  #   runs-on: self-hosted
  #   steps:  
  #     - name: Run Container
  #       run: |
  #         docker run --rm jaz-test:latest
